python snapshot28_ytclump_fields.py 16 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_16/ && echo "Done with snapshot 16" || echo "snapshot 16 Failed " &&
python snapshot28_ytclump_fields.py 17 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_17/ && echo "Done with snapshot 17" || echo "snapshot 17 Failed " &&
python snapshot28_ytclump_fields.py 18 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_18/ && echo "Done with snapshot 18" || echo "snapshot 18 Failed " &&
python snapshot28_ytclump_fields.py 19 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_19/ && echo "Done with snapshot 19" || echo "snapshot 19 Failed " &&
python snapshot28_ytclump_fields.py 20 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_20/ && echo "Done with snapshot 20" || echo "snapshot 20 Failed " &&
python snapshot28_ytclump_fields.py 21 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_21/ && echo "Done with snapshot 21" || echo "snapshot 21 Failed " &&
python snapshot28_ytclump_fields.py 22 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_22/ && echo "Done with snapshot 22" || echo "snapshot 22 Failed " &&
python snapshot28_ytclump_fields.py 23 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_23/ && echo "Done with snapshot 23" || echo "snapshot 23 Failed " &&
python snapshot28_ytclump_fields.py 24 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_24/ && echo "Done with snapshot 24" || echo "snapshot 24 Failed " &&
python snapshot28_ytclump_fields.py 25 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_25/ && echo "Done with snapshot 25" || echo "snapshot 25 Failed " &&
python snapshot28_ytclump_fields.py 26 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_26/ && echo "Done with snapshot 26" || echo "snapshot 26 Failed " &&
python snapshot28_ytclump_fields.py 27 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_27/ && echo "Done with snapshot 27" || echo "snapshot 27 Failed " &&
python snapshot28_ytclump_fields.py 28 -nc 1.0 -nm 10 --savepickle --plot --saveplot test_png_28/ && echo "Done with snapshot 28" || echo "snapshot 28 Failed "
python snapshot28_ytclump_fields.py 16 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_16/ && echo "Done with snapshot 16" || echo "snapshot 16 Failed " &&
python snapshot28_ytclump_fields.py 17 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_17/ && echo "Done with snapshot 17" || echo "snapshot 17 Failed " &&
python snapshot28_ytclump_fields.py 18 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_18/ && echo "Done with snapshot 18" || echo "snapshot 18 Failed " &&
python snapshot28_ytclump_fields.py 19 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_19/ && echo "Done with snapshot 19" || echo "snapshot 19 Failed " &&
python snapshot28_ytclump_fields.py 20 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_20/ && echo "Done with snapshot 20" || echo "snapshot 20 Failed " &&
python snapshot28_ytclump_fields.py 21 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_21/ && echo "Done with snapshot 21" || echo "snapshot 21 Failed " &&
python snapshot28_ytclump_fields.py 22 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_22/ && echo "Done with snapshot 22" || echo "snapshot 22 Failed " &&
python snapshot28_ytclump_fields.py 23 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_23/ && echo "Done with snapshot 23" || echo "snapshot 23 Failed " &&
python snapshot28_ytclump_fields.py 24 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_24/ && echo "Done with snapshot 24" || echo "snapshot 24 Failed " &&
python snapshot28_ytclump_fields.py 25 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_25/ && echo "Done with snapshot 25" || echo "snapshot 25 Failed " &&
python snapshot28_ytclump_fields.py 26 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_26/ && echo "Done with snapshot 26" || echo "snapshot 26 Failed " &&
python snapshot28_ytclump_fields.py 27 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_27/ && echo "Done with snapshot 27" || echo "snapshot 27 Failed " &&
python snapshot28_ytclump_fields.py 28 -nc 0.7 -nm 10 --savepickle --plot --saveplot test_png_28/ && echo "Done with snapshot 28" || echo "snapshot 28 Failed "
python snapshot28_ytclump_fields.py 16 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_16/ && echo "Done with snapshot 16" || echo "snapshot 16 Failed " &&
python snapshot28_ytclump_fields.py 17 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_17/ && echo "Done with snapshot 17" || echo "snapshot 17 Failed " &&
python snapshot28_ytclump_fields.py 18 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_18/ && echo "Done with snapshot 18" || echo "snapshot 18 Failed " &&
python snapshot28_ytclump_fields.py 19 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_19/ && echo "Done with snapshot 19" || echo "snapshot 19 Failed " &&
python snapshot28_ytclump_fields.py 20 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_20/ && echo "Done with snapshot 20" || echo "snapshot 20 Failed " &&
python snapshot28_ytclump_fields.py 21 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_21/ && echo "Done with snapshot 21" || echo "snapshot 21 Failed " &&
python snapshot28_ytclump_fields.py 22 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_22/ && echo "Done with snapshot 22" || echo "snapshot 22 Failed " &&
python snapshot28_ytclump_fields.py 23 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_23/ && echo "Done with snapshot 23" || echo "snapshot 23 Failed " &&
python snapshot28_ytclump_fields.py 24 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_24/ && echo "Done with snapshot 24" || echo "snapshot 24 Failed " &&
python snapshot28_ytclump_fields.py 25 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_25/ && echo "Done with snapshot 25" || echo "snapshot 25 Failed " &&
python snapshot28_ytclump_fields.py 26 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_26/ && echo "Done with snapshot 26" || echo "snapshot 26 Failed " &&
python snapshot28_ytclump_fields.py 27 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_27/ && echo "Done with snapshot 27" || echo "snapshot 27 Failed " &&
python snapshot28_ytclump_fields.py 28 -nc 0.1 -nm 10 --savepickle --plot --saveplot test_png_28/ && echo "Done with snapshot 28" || echo "snapshot 28 Failed "
python snapshot28_ytclump_fields.py 16 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_16/ && echo "Done with snapshot 16" || echo "snapshot 16 Failed " &&
python snapshot28_ytclump_fields.py 17 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_17/ && echo "Done with snapshot 17" || echo "snapshot 17 Failed " &&
python snapshot28_ytclump_fields.py 18 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_18/ && echo "Done with snapshot 18" || echo "snapshot 18 Failed " &&
python snapshot28_ytclump_fields.py 19 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_19/ && echo "Done with snapshot 19" || echo "snapshot 19 Failed " &&
python snapshot28_ytclump_fields.py 20 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_20/ && echo "Done with snapshot 20" || echo "snapshot 20 Failed " &&
python snapshot28_ytclump_fields.py 21 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_21/ && echo "Done with snapshot 21" || echo "snapshot 21 Failed " &&
python snapshot28_ytclump_fields.py 22 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_22/ && echo "Done with snapshot 22" || echo "snapshot 22 Failed " &&
python snapshot28_ytclump_fields.py 23 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_23/ && echo "Done with snapshot 23" || echo "snapshot 23 Failed " &&
python snapshot28_ytclump_fields.py 24 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_24/ && echo "Done with snapshot 24" || echo "snapshot 24 Failed " &&
python snapshot28_ytclump_fields.py 25 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_25/ && echo "Done with snapshot 25" || echo "snapshot 25 Failed " &&
python snapshot28_ytclump_fields.py 26 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_26/ && echo "Done with snapshot 26" || echo "snapshot 26 Failed " &&
python snapshot28_ytclump_fields.py 27 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_27/ && echo "Done with snapshot 27" || echo "snapshot 27 Failed " &&
python snapshot28_ytclump_fields.py 28 -nc 0.5 -nm 10 --savepickle --plot --saveplot test_png_28/ && echo "Done with snapshot 28" || echo "snapshot 28 Failed "